package com.aral.recyclerview

object MockList {

    fun getMockedItemList(): List<ItemModel> {
        return ArrayList<ItemModel>()
            .apply {
                add(
                    ItemModel(
                        R.drawable.facebook,
                        "FACEBOOK",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.instagram,
                        "INSTAGRAM",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.whatsapp,
                        "WHATSAPP",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.youtube,
                        "YOUTUBE",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.youtube,
                        "YOUTUBE",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.twitter,
                        "TWITTER",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.twitter,
                        "TWITTER",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.linkedin,
                        "LINKEDIN",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.skype,
                        "SKYPE",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.snapchat,
                        "SNAPCHAT",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.whatsapp,
                        "WHATSAPP",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.instagram,
                        "INSTAGRAM",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.linkedin,
                        "LINKEDIN",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.skype,
                        "SKYPE",
                    )
                )
                add(
                    ItemModel(
                        R.drawable.instagram,
                        "INSTAGRAM",
                    )
                )
            }
    }
}